import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import {
  HelpCircle, MessageSquare, Music, ChevronDown, ChevronUp,
  Send, Loader2, ArrowLeft, Shield, Zap, FileText, CreditCard,
  Headphones, BarChart3
} from "lucide-react";
import { useLocation } from "wouter";

const FAQ_ITEMS = [
  {
    category: "Getting Started",
    icon: Music,
    items: [
      {
        q: "How does Troubadour analyze my music?",
        a: "Troubadour uses AI audio intelligence to listen to your tracks and generate comprehensive critiques. Upload your audio file, and the engine analyzes songwriting, production quality, arrangement, performance, and commercial potential — delivering a detailed review with specific, actionable feedback.",
      },
      {
        q: "What audio formats are supported?",
        a: "We support MP3, WAV, FLAC, AAC, OGG, and WebM audio formats. Files up to 50MB are accepted. For best results, upload high-quality audio (WAV or 320kbps MP3).",
      },
      {
        q: "How long does a review take?",
        a: "Most reviews complete within 2–5 minutes depending on track length and server load. You'll receive a notification when your review is ready. You can continue uploading other tracks while waiting.",
      },
    ],
  },
  {
    category: "Reviews & Features",
    icon: FileText,
    items: [
      {
        q: "What dimensions does a review cover?",
        a: "Every review covers five dimensions: Songwriting & Melody (hooks, lyrics, structure), Production & Mix (sonic quality, balance, effects), Arrangement (instrumentation, dynamics, transitions), Performance (vocal/instrumental delivery, emotion), and Commercial Potential (market readiness, genre fit, audience appeal).",
      },
      {
        q: "Can I compare different versions of a track?",
        a: "Yes. Upload a new version of any track and Troubadour will generate a side-by-side comparison showing exactly what improved, what regressed, and what stayed the same across all dimensions.",
      },
      {
        q: "What are Action Modes?",
        a: "Action Modes reshape your review into goal-oriented formats: Session Prep (prioritized fixes for your next studio session), Pitch Ready (A&R-friendly summary), Rewrite Focus (songwriting-specific notes), and Remix Focus (production-specific notes). Each mode can be exported as a formatted document.",
      },
      {
        q: "Can I ask follow-up questions about a review?",
        a: "Yes. Every review has a conversation panel where you can ask the AI to clarify any part of the critique. Questions like 'What did you mean about the chorus not lifting?' get grounded, specific answers based on what the engine actually heard.",
      },
    ],
  },
  {
    category: "Billing & Plans",
    icon: CreditCard,
    items: [
      {
        q: "What's included in the free plan?",
        a: "The free plan includes 3 reviews per month, 60 minutes of audio analysis, and access to all core review features. Upgrade to Artist ($19/mo) or Pro ($49/mo) for unlimited reviews, more audio minutes, and advanced features like Action Modes and priority processing.",
      },
      {
        q: "How do I cancel my subscription?",
        a: "Go to Settings → Subscription → Manage Billing. This opens the Stripe billing portal where you can cancel, change plans, or update payment methods. Your access continues until the end of the current billing period.",
      },
      {
        q: "Is my payment information secure?",
        a: "All payments are processed through Stripe, a PCI-DSS Level 1 certified payment processor. We never store your card details — Stripe handles all sensitive payment data.",
      },
    ],
  },
  {
    category: "Privacy & Data",
    icon: Shield,
    items: [
      {
        q: "Is my music kept private?",
        a: "Yes. Your uploaded audio files and reviews are private by default. Only you can access them unless you explicitly share a review using the share feature. We do not use your music for training AI models.",
      },
      {
        q: "Can I delete my data?",
        a: "Yes. Go to Settings → Danger Zone → Delete Account. This permanently removes your account, all projects, tracks, reviews, and associated data. You can also delete individual projects or tracks at any time.",
      },
      {
        q: "Are reviews generated by AI?",
        a: "Yes. All reviews are AI-generated and should be used as a creative tool alongside your own musical instincts and judgment. The AI provides structured analysis, but the final creative decisions are always yours.",
      },
    ],
  },
];

export default function Support() {
  const [, setLocation] = useLocation();
  const { user } = useAuth();
  const [expandedFaq, setExpandedFaq] = useState<string | null>(null);
  const [subject, setSubject] = useState("");
  const [message, setMessage] = useState("");
  const [sending, setSending] = useState(false);

  const contactMutation = trpc.support.sendMessage.useMutation({
    onSuccess: () => {
      toast.success("Message sent! We'll get back to you soon.");
      setSubject("");
      setMessage("");
    },
    onError: (err) => {
      toast.error(err.message || "Failed to send message");
    },
    onSettled: () => setSending(false),
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!subject.trim() || !message.trim()) {
      toast.error("Please fill in both subject and message");
      return;
    }
    setSending(true);
    contactMutation.mutate({ subject: subject.trim(), message: message.trim() });
  };

  const toggleFaq = (key: string) => {
    setExpandedFaq(prev => prev === key ? null : key);
  };

  return (
    <div className="min-h-screen bg-background text-foreground">
      {/* Header */}
      <div className="border-b border-border/30 bg-background/80 backdrop-blur-xl">
        <div className="container max-w-4xl py-8">
          <Button
            variant="ghost"
            size="sm"
            className="mb-4 text-muted-foreground"
            onClick={() => setLocation(user ? "/dashboard" : "/")}
          >
            <ArrowLeft className="h-4 w-4 mr-1" />
            {user ? "Back to Dashboard" : "Back to Home"}
          </Button>
          <div className="flex items-center gap-3 mb-2">
            <div className="p-2 rounded-xl bg-primary/10">
              <HelpCircle className="h-6 w-6 text-primary" />
            </div>
            <h1 className="text-3xl font-bold tracking-tight" style={{ fontFamily: "'Space Grotesk', system-ui, sans-serif" }}>
              Help & Support
            </h1>
          </div>
          <p className="text-muted-foreground max-w-xl">
            Find answers to common questions or get in touch with our team.
          </p>
        </div>
      </div>

      <div className="container max-w-4xl py-10 space-y-12">
        {/* FAQ Section */}
        <section>
          <h2 className="text-xl font-semibold mb-6" style={{ fontFamily: "'Space Grotesk', system-ui, sans-serif" }}>
            Frequently Asked Questions
          </h2>
          <div className="space-y-6">
            {FAQ_ITEMS.map((category) => {
              const Icon = category.icon;
              return (
                <div key={category.category}>
                  <div className="flex items-center gap-2 mb-3">
                    <Icon className="h-4 w-4 text-primary" />
                    <h3 className="text-sm font-semibold text-muted-foreground uppercase tracking-wider">
                      {category.category}
                    </h3>
                  </div>
                  <div className="space-y-1">
                    {category.items.map((faq, idx) => {
                      const key = `${category.category}-${idx}`;
                      const isOpen = expandedFaq === key;
                      return (
                        <Card key={key} className="border-border/40 overflow-hidden">
                          <button
                            onClick={() => toggleFaq(key)}
                            className="w-full text-left px-5 py-4 flex items-center justify-between gap-3 hover:bg-muted/20 transition-colors"
                          >
                            <span className="text-sm font-medium">{faq.q}</span>
                            {isOpen ? (
                              <ChevronUp className="h-4 w-4 text-muted-foreground shrink-0" />
                            ) : (
                              <ChevronDown className="h-4 w-4 text-muted-foreground shrink-0" />
                            )}
                          </button>
                          {isOpen && (
                            <div className="px-5 pb-4 border-t border-border/20">
                              <p className="text-sm text-muted-foreground leading-relaxed pt-3">
                                {faq.a}
                              </p>
                            </div>
                          )}
                        </Card>
                      );
                    })}
                  </div>
                </div>
              );
            })}
          </div>
        </section>

        {/* Contact Form */}
        <section>
          <h2 className="text-xl font-semibold mb-2" style={{ fontFamily: "'Space Grotesk', system-ui, sans-serif" }}>
            Contact Us
          </h2>
          <p className="text-sm text-muted-foreground mb-6">
            Can't find what you're looking for? Send us a message and we'll get back to you.
          </p>

          {user ? (
            <Card className="border-border/40">
              <CardContent className="pt-6">
                <form onSubmit={handleSubmit} className="space-y-4">
                  <div>
                    <label className="text-sm font-medium mb-1.5 block">Subject</label>
                    <Input
                      placeholder="What can we help with?"
                      value={subject}
                      onChange={(e) => setSubject(e.target.value)}
                      maxLength={200}
                    />
                  </div>
                  <div>
                    <label className="text-sm font-medium mb-1.5 block">Message</label>
                    <Textarea
                      placeholder="Describe your issue or question in detail..."
                      value={message}
                      onChange={(e) => setMessage(e.target.value)}
                      rows={6}
                      maxLength={5000}
                    />
                    <p className="text-xs text-muted-foreground mt-1 text-right">
                      {message.length}/5000
                    </p>
                  </div>
                  <div className="flex items-center justify-between">
                    <p className="text-xs text-muted-foreground">
                      Sending as {user.name || user.email || "your account"}
                    </p>
                    <Button type="submit" disabled={sending || !subject.trim() || !message.trim()}>
                      {sending ? (
                        <><Loader2 className="h-4 w-4 mr-2 animate-spin" /> Sending...</>
                      ) : (
                        <><Send className="h-4 w-4 mr-2" /> Send Message</>
                      )}
                    </Button>
                  </div>
                </form>
              </CardContent>
            </Card>
          ) : (
            <Card className="border-border/40">
              <CardContent className="py-8 text-center">
                <MessageSquare className="h-10 w-10 text-muted-foreground/30 mx-auto mb-3" />
                <p className="text-sm text-muted-foreground mb-4">
                  Sign in to send us a message. We'll respond to the email on your account.
                </p>
                <Button onClick={() => { window.location.href = "/api/login"; }}>
                  Sign In to Contact Support
                </Button>
              </CardContent>
            </Card>
          )}
        </section>

        {/* Quick Links */}
        <section className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          <Card className="border-border/40 hover:border-primary/30 transition-colors cursor-pointer" onClick={() => setLocation("/terms")}>
            <CardContent className="py-5 flex items-center gap-3">
              <FileText className="h-5 w-5 text-muted-foreground" />
              <div>
                <p className="text-sm font-medium">Terms of Service</p>
                <p className="text-xs text-muted-foreground">Usage policies</p>
              </div>
            </CardContent>
          </Card>
          <Card className="border-border/40 hover:border-primary/30 transition-colors cursor-pointer" onClick={() => setLocation("/privacy")}>
            <CardContent className="py-5 flex items-center gap-3">
              <Shield className="h-5 w-5 text-muted-foreground" />
              <div>
                <p className="text-sm font-medium">Privacy Policy</p>
                <p className="text-xs text-muted-foreground">Data handling</p>
              </div>
            </CardContent>
          </Card>
          <Card className="border-border/40 hover:border-primary/30 transition-colors cursor-pointer" onClick={() => setLocation("/pricing")}>
            <CardContent className="py-5 flex items-center gap-3">
              <CreditCard className="h-5 w-5 text-muted-foreground" />
              <div>
                <p className="text-sm font-medium">Pricing</p>
                <p className="text-xs text-muted-foreground">Plans & billing</p>
              </div>
            </CardContent>
          </Card>
        </section>
      </div>
    </div>
  );
}
