import { ArrowLeft } from "lucide-react";
import { Link } from "wouter";

export default function Terms() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="container max-w-3xl py-12">
        <Link href="/" className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground mb-8">
          <ArrowLeft className="h-4 w-4" />
          Back to Home
        </Link>

        <h1 className="text-3xl font-bold mb-2" style={{ fontFamily: "'Space Grotesk', system-ui, sans-serif" }}>
          Terms of Service
        </h1>
        <p className="text-sm text-muted-foreground mb-8">Last updated: February 18, 2026</p>

        <div className="prose prose-invert prose-sm max-w-none space-y-6">
          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">1. Acceptance of Terms</h2>
            <p className="text-muted-foreground leading-relaxed">
              By accessing or using Troubadour ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, you may not use the Service. Troubadour reserves the right to update these terms at any time, and continued use constitutes acceptance of any changes.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">2. Description of Service</h2>
            <p className="text-muted-foreground leading-relaxed">
              Troubadour is an AI-powered music critique platform that provides automated analysis and feedback on audio tracks. Reviews, scores, and suggestions are generated by artificial intelligence and should be treated as one perspective among many. AI-generated content does not constitute professional music production advice, and results may vary in accuracy and relevance.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">3. User Accounts</h2>
            <p className="text-muted-foreground leading-relaxed">
              You are responsible for maintaining the security of your account and for all activities that occur under your account. You must provide accurate information when creating your account. Troubadour reserves the right to suspend or terminate accounts that violate these terms.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">4. Intellectual Property</h2>
            <p className="text-muted-foreground leading-relaxed">
              You retain all rights to the audio content you upload. By uploading content, you grant Troubadour a limited, non-exclusive license to process your audio for the purpose of generating reviews and analysis. Troubadour does not claim ownership of your music. AI-generated reviews are provided for your personal use and may be shared or exported at your discretion.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">5. Acceptable Use</h2>
            <p className="text-muted-foreground leading-relaxed">
              You agree not to upload content that infringes on the intellectual property rights of others, contains illegal material, or is designed to abuse or overload the Service. Automated bulk uploads or attempts to reverse-engineer the AI system are prohibited.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">6. Payment & Subscriptions</h2>
            <p className="text-muted-foreground leading-relaxed">
              Paid plans are billed monthly through Stripe. You may cancel your subscription at any time, and cancellation takes effect at the end of the current billing period. Refunds are handled on a case-by-case basis. Troubadour reserves the right to change pricing with 30 days' notice.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">7. AI-Generated Content Disclaimer</h2>
            <p className="text-muted-foreground leading-relaxed">
              All reviews, scores, and suggestions generated by Troubadour are produced by artificial intelligence. These outputs are algorithmic in nature and may contain errors, biases, or inaccuracies. They do not represent the opinions of any human reviewer. Troubadour makes no guarantees about the accuracy, completeness, or suitability of AI-generated feedback for any particular purpose.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">8. Limitation of Liability</h2>
            <p className="text-muted-foreground leading-relaxed">
              Troubadour is provided "as is" without warranties of any kind. In no event shall Troubadour be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service. Our total liability shall not exceed the amount you paid for the Service in the 12 months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">9. Data Retention</h2>
            <p className="text-muted-foreground leading-relaxed">
              Uploaded audio files and generated reviews are stored for the duration of your account. You may delete your content at any time. Upon account deletion, your data will be removed within 30 days, except where retention is required by law.
            </p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-foreground mb-3">10. Contact</h2>
            <p className="text-muted-foreground leading-relaxed">
              For questions about these terms, please reach out through the Support section in your account settings.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
