import { describe, it, expect, vi } from "vitest";

// ── Support Page Structure Tests ──
describe("Support page structure", () => {
  it("FAQ_ITEMS covers all four categories", async () => {
    // Read the Support page source to verify FAQ structure
    const fs = await import("fs");
    const source = fs.readFileSync("client/src/pages/Support.tsx", "utf-8");
    expect(source).toContain('"Getting Started"');
    expect(source).toContain('"Reviews & Features"');
    expect(source).toContain('"Billing & Plans"');
    expect(source).toContain('"Privacy & Data"');
  });

  it("FAQ includes AI disclosure question", async () => {
    const fs = await import("fs");
    const source = fs.readFileSync("client/src/pages/Support.tsx", "utf-8");
    expect(source).toContain("Are reviews generated by AI?");
    expect(source).toContain("AI-generated and should be used as a creative tool");
  });

  it("FAQ includes privacy question about music data", async () => {
    const fs = await import("fs");
    const source = fs.readFileSync("client/src/pages/Support.tsx", "utf-8");
    expect(source).toContain("Is my music kept private?");
    expect(source).toContain("do not use your music for training AI models");
  });

  it("FAQ includes payment security question referencing Stripe PCI-DSS", async () => {
    const fs = await import("fs");
    const source = fs.readFileSync("client/src/pages/Support.tsx", "utf-8");
    expect(source).toContain("Is my payment information secure?");
    expect(source).toContain("PCI-DSS Level 1");
    expect(source).toContain("never store your card details");
  });

  it("Contact form uses trpc.support.sendMessage mutation", async () => {
    const fs = await import("fs");
    const source = fs.readFileSync("client/src/pages/Support.tsx", "utf-8");
    expect(source).toContain("trpc.support.sendMessage.useMutation");
  });

  it("Contact form has subject and message fields with max lengths", async () => {
    const fs = await import("fs");
    const source = fs.readFileSync("client/src/pages/Support.tsx", "utf-8");
    expect(source).toContain('maxLength={200}');
    expect(source).toContain('maxLength={5000}');
  });

  it("Shows sign-in prompt for unauthenticated users", async () => {
    const fs = await import("fs");
    const source = fs.readFileSync("client/src/pages/Support.tsx", "utf-8");
    expect(source).toContain("Sign in to send us a message");
  });

  it("Quick links section includes Terms, Privacy, and Pricing", async () => {
    const fs = await import("fs");
    const source = fs.readFileSync("client/src/pages/Support.tsx", "utf-8");
    expect(source).toContain('setLocation("/terms")');
    expect(source).toContain('setLocation("/privacy")');
    expect(source).toContain('setLocation("/pricing")');
  });
});

// ── Support Router Tests ──
describe("Support router", () => {
  it("support.sendMessage procedure exists with correct input schema", async () => {
    const fs = await import("fs");
    const source = fs.readFileSync("server/routers.ts", "utf-8");
    expect(source).toContain("support: router({");
    expect(source).toContain("sendMessage: protectedProcedure");
    expect(source).toContain('subject: z.string().min(1).max(200)');
    expect(source).toContain('message: z.string().min(1).max(5000)');
  });

  it("support.sendMessage notifies owner and sends confirmation email", async () => {
    const fs = await import("fs");
    const source = fs.readFileSync("server/routers.ts", "utf-8");
    expect(source).toContain("notifyOwner");
    expect(source).toContain("[Support]");
    expect(source).toContain("We received your message");
  });
});

// ── Platform Stats Tests ──
describe("Platform stats", () => {
  it("platform.stats is a public procedure", async () => {
    const fs = await import("fs");
    const source = fs.readFileSync("server/routers.ts", "utf-8");
    expect(source).toContain("platform: router({");
    expect(source).toContain("stats: publicProcedure.query");
  });

  it("getPlatformStats function exists in db.ts", async () => {
    const fs = await import("fs");
    const source = fs.readFileSync("server/db.ts", "utf-8");
    expect(source).toContain("export async function getPlatformStats()");
    expect(source).toContain("totalReviews");
    expect(source).toContain("totalTracks");
    expect(source).toContain("totalProjects");
    expect(source).toContain("totalUsers");
  });

  it("getPlatformStats returns safe defaults when db is unavailable", async () => {
    const fs = await import("fs");
    const source = fs.readFileSync("server/db.ts", "utf-8");
    // Check that it returns 0 defaults
    expect(source).toContain("totalReviews: 0, totalTracks: 0, totalProjects: 0, totalUsers: 0");
  });
});

// ── Social Proof Landing Page Tests ──
describe("Social proof on landing page", () => {
  it("Home.tsx includes SocialProofBar component", async () => {
    const fs = await import("fs");
    const source = fs.readFileSync("client/src/pages/Home.tsx", "utf-8");
    expect(source).toContain("<SocialProofBar />");
    expect(source).toContain("function SocialProofBar()");
  });

  it("SocialProofBar uses trpc.platform.stats.useQuery", async () => {
    const fs = await import("fs");
    const source = fs.readFileSync("client/src/pages/Home.tsx", "utf-8");
    expect(source).toContain("trpc.platform.stats.useQuery");
  });

  it("SocialProofBar shows animated counters for reviews, tracks, projects", async () => {
    const fs = await import("fs");
    const source = fs.readFileSync("client/src/pages/Home.tsx", "utf-8");
    expect(source).toContain("Reviews Generated");
    expect(source).toContain("Tracks Analyzed");
    expect(source).toContain("Projects Created");
    expect(source).toContain("Review Dimensions");
  });

  it("AnimatedCounter component handles large numbers with k suffix", async () => {
    const fs = await import("fs");
    const source = fs.readFileSync("client/src/pages/Home.tsx", "utf-8");
    expect(source).toContain("function AnimatedCounter");
    expect(source).toContain(".toFixed(1)}k");
  });

  it("Trust signals section includes security, payments, free tier, and AI badges", async () => {
    const fs = await import("fs");
    const source = fs.readFileSync("client/src/pages/Home.tsx", "utf-8");
    expect(source).toContain("Secure & Private");
    expect(source).toContain("Stripe Payments");
    expect(source).toContain("Free Tier Available");
    expect(source).toContain("AI-Powered Analysis");
  });
});

// ── Footer Links Tests ──
describe("Footer includes support link", () => {
  it("Home.tsx footer has support link in Product section", async () => {
    const fs = await import("fs");
    const source = fs.readFileSync("client/src/pages/Home.tsx", "utf-8");
    expect(source).toContain('href="/support"');
  });

  it("Home.tsx footer has support link in Legal section", async () => {
    const fs = await import("fs");
    const source = fs.readFileSync("client/src/pages/Home.tsx", "utf-8");
    expect(source).toContain("Help & Support");
  });
});

// ── Route Registration Tests ──
describe("Route registration", () => {
  it("App.tsx includes /support route", async () => {
    const fs = await import("fs");
    const source = fs.readFileSync("client/src/App.tsx", "utf-8");
    expect(source).toContain('"/support"');
    expect(source).toContain("Support");
  });
});
