import { describe, it, expect } from "vitest";
import fs from "fs";

describe("Round 62b — Governance & Audit Improvements", () => {
  describe("Terms of Service Page", () => {
    it("Terms.tsx page file exists", () => {
      expect(fs.existsSync("/home/ubuntu/ai-album-critic/client/src/pages/Terms.tsx")).toBe(true);
    });

    it("Terms page contains required legal sections", () => {
      const content = fs.readFileSync("/home/ubuntu/ai-album-critic/client/src/pages/Terms.tsx", "utf-8");
      expect(content).toContain("Terms of Service");
      expect(content).toContain("Acceptance of Terms");
      expect(content).toContain("Intellectual Property");
      expect(content).toContain("AI-Generated Content Disclaimer");
      expect(content).toContain("Limitation of Liability");
      expect(content).toContain("Payment & Subscriptions");
      expect(content).toContain("Data Retention");
    });

    it("Terms page has back navigation to home", () => {
      const content = fs.readFileSync("/home/ubuntu/ai-album-critic/client/src/pages/Terms.tsx", "utf-8");
      expect(content).toContain('href="/"');
      expect(content).toContain("Back to Home");
    });
  });

  describe("Privacy Policy Page", () => {
    it("Privacy.tsx page file exists", () => {
      expect(fs.existsSync("/home/ubuntu/ai-album-critic/client/src/pages/Privacy.tsx")).toBe(true);
    });

    it("Privacy page contains required sections", () => {
      const content = fs.readFileSync("/home/ubuntu/ai-album-critic/client/src/pages/Privacy.tsx", "utf-8");
      expect(content).toContain("Privacy Policy");
      expect(content).toContain("Information We Collect");
      expect(content).toContain("Audio File Processing");
      expect(content).toContain("AI Processing");
      expect(content).toContain("Payment Information");
      expect(content).toContain("Data Security");
      expect(content).toContain("Your Rights");
    });

    it("Privacy page mentions Stripe for payment processing", () => {
      const content = fs.readFileSync("/home/ubuntu/ai-album-critic/client/src/pages/Privacy.tsx", "utf-8");
      expect(content).toContain("Stripe");
    });
  });

  describe("Route Registration", () => {
    it("App.tsx registers /terms and /privacy routes", () => {
      const content = fs.readFileSync("/home/ubuntu/ai-album-critic/client/src/App.tsx", "utf-8");
      expect(content).toContain('path="/terms"');
      expect(content).toContain('path="/privacy"');
      expect(content).toContain("import Terms");
      expect(content).toContain("import Privacy");
    });
  });

  describe("AI Disclaimer in Review View", () => {
    it("ReviewView.tsx contains AI-generated disclaimer", () => {
      const content = fs.readFileSync("/home/ubuntu/ai-album-critic/client/src/pages/ReviewView.tsx", "utf-8");
      expect(content).toContain("generated by AI");
      expect(content).toContain("algorithmic analysis");
      expect(content).toContain("not human judgment");
    });
  });

  describe("AI Disclaimer in PDF Export", () => {
    it("pdfExport.ts contains AI-generated disclaimer in footer", () => {
      const content = fs.readFileSync("/home/ubuntu/ai-album-critic/server/services/pdfExport.ts", "utf-8");
      expect(content).toContain("generated by artificial intelligence");
      expect(content).toContain("algorithmic analysis, not human judgment");
    });
  });

  describe("Footer Improvements", () => {
    it("Home.tsx footer contains legal links", () => {
      const content = fs.readFileSync("/home/ubuntu/ai-album-critic/client/src/pages/Home.tsx", "utf-8");
      expect(content).toContain('href="/terms"');
      expect(content).toContain('href="/privacy"');
      expect(content).toContain("Terms of Service");
      expect(content).toContain("Privacy Policy");
    });

    it("Home.tsx footer contains AI-generated notice", () => {
      const content = fs.readFileSync("/home/ubuntu/ai-album-critic/client/src/pages/Home.tsx", "utf-8");
      expect(content).toContain("All reviews are AI-generated");
    });

    it("Home.tsx footer has proper grid structure", () => {
      const content = fs.readFileSync("/home/ubuntu/ai-album-critic/client/src/pages/Home.tsx", "utf-8");
      expect(content).toContain("grid grid-cols-1 md:grid-cols-4");
      expect(content).toContain("Product");
      expect(content).toContain("Legal");
    });

    it("Pricing.tsx has legal links in footer", () => {
      const content = fs.readFileSync("/home/ubuntu/ai-album-critic/client/src/pages/Pricing.tsx", "utf-8");
      expect(content).toContain('href="/terms"');
      expect(content).toContain('href="/privacy"');
    });
  });

  describe("Checkout Opens in New Tab", () => {
    it("Pricing.tsx uses window.open for checkout", () => {
      const content = fs.readFileSync("/home/ubuntu/ai-album-critic/client/src/pages/Pricing.tsx", "utf-8");
      expect(content).toContain("window.open(data.url, '_blank')");
    });
  });

  describe("BatchActionsToolbar TypeScript Fix", () => {
    it("BatchActionsToolbar uses proper tRPC mutations", () => {
      const content = fs.readFileSync("/home/ubuntu/ai-album-critic/client/src/components/BatchActionsToolbar.tsx", "utf-8");
      expect(content).toContain("trpc.tags.update.useMutation");
      expect(content).toContain("trpc.track.deleteTrack.useMutation");
      expect(content).not.toContain("fetch(`/api/trpc/track.deleteTrack`");
    });
  });

  describe("Gravito Audit Documentation", () => {
    it("Gravito audit results file exists", () => {
      expect(fs.existsSync("/home/ubuntu/ai-album-critic/gravito-audit-results.md")).toBe(true);
    });

    it("Gravito audit results contain governance assessment", () => {
      const content = fs.readFileSync("/home/ubuntu/ai-album-critic/gravito-audit-results.md", "utf-8");
      expect(content).toContain("Gravito Governance Audit");
      expect(content).toContain("Manual Governance Assessment");
      expect(content).toContain("Recommendations");
    });
  });
});
