import { marked } from "marked";
import { storagePut } from "../storage";

const PDF_CSS = `
  @page { margin: 40px 50px; size: A4; }
  body {
    font-family: 'Segoe UI', 'Helvetica Neue', Arial, sans-serif;
    font-size: 11pt;
    line-height: 1.6;
    color: #1a1a2e;
    max-width: 100%;
  }
  .header {
    border-bottom: 3px solid #6366f1;
    padding-bottom: 12px;
    margin-bottom: 20px;
  }
  .header h1 {
    font-size: 22pt;
    color: #1a1a2e;
    margin: 0 0 4px 0;
    font-weight: 700;
  }
  .header .subtitle {
    font-size: 10pt;
    color: #6366f1;
    font-weight: 600;
    text-transform: uppercase;
    letter-spacing: 1px;
  }
  .header .meta {
    font-size: 9pt;
    color: #64748b;
    margin-top: 6px;
  }
  .scores-grid {
    display: flex;
    flex-wrap: wrap;
    gap: 8px;
    margin: 16px 0;
  }
  .score-pill {
    background: #f1f5f9;
    border-radius: 20px;
    padding: 4px 14px;
    font-size: 9pt;
    font-weight: 600;
    color: #334155;
    border: 1px solid #e2e8f0;
  }
  .score-pill .val {
    color: #6366f1;
    font-weight: 700;
  }
  .quick-take {
    background: #f8fafc;
    border-left: 4px solid #6366f1;
    padding: 12px 16px;
    margin: 16px 0;
    font-style: italic;
    color: #334155;
    font-size: 10.5pt;
  }
  h2 {
    font-size: 14pt;
    color: #1a1a2e;
    border-bottom: 1px solid #e2e8f0;
    padding-bottom: 6px;
    margin-top: 24px;
    margin-bottom: 12px;
  }
  h3 {
    font-size: 12pt;
    color: #334155;
    margin-top: 18px;
    margin-bottom: 8px;
  }
  ul, ol {
    padding-left: 24px;
    margin: 8px 0;
  }
  li {
    margin-bottom: 4px;
  }
  strong {
    color: #1a1a2e;
  }
  p {
    margin: 8px 0;
  }
  .footer {
    margin-top: 30px;
    padding-top: 12px;
    border-top: 1px solid #e2e8f0;
    font-size: 8pt;
    color: #94a3b8;
    text-align: center;
  }
  table {
    width: 100%;
    border-collapse: collapse;
    margin: 12px 0;
  }
  th, td {
    padding: 6px 12px;
    text-align: left;
    border-bottom: 1px solid #e2e8f0;
    font-size: 10pt;
  }
  th {
    background: #f1f5f9;
    font-weight: 600;
    color: #334155;
  }
`;

interface PdfExportOptions {
  trackName: string;
  genre?: string;
  quickTake?: string | null;
  scores?: Record<string, number> | null;
  content: string;
  mode: string;
  modeLabel: string;
  date: Date;
}

export async function generateReviewPdfHtml(opts: PdfExportOptions): Promise<string> {
  const contentHtml = await marked.parse(opts.content);

  const scorePills = opts.scores && Object.keys(opts.scores).length > 0
    ? `<div class="scores-grid">${Object.entries(opts.scores)
        .map(([k, v]) => {
          const label = k.replace(/([A-Z])/g, " $1").replace(/^./, s => s.toUpperCase()).trim();
          return `<span class="score-pill">${label}: <span class="val">${v}/10</span></span>`;
        })
        .join("")}</div>`
    : "";

  const quickTakeHtml = opts.quickTake
    ? `<div class="quick-take">${opts.quickTake}</div>`
    : "";

  const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>${PDF_CSS}</style>
</head>
<body>
  <div class="header">
    <div class="subtitle">Troubadour — ${opts.modeLabel}</div>
    <h1>${escapeHtml(opts.trackName)}</h1>
    <div class="meta">
      ${opts.genre ? `Genre: ${escapeHtml(opts.genre)} · ` : ""}Generated ${opts.date.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
    </div>
  </div>
  ${quickTakeHtml}
  ${scorePills}
  <div class="content">
    ${contentHtml}
  </div>
  <div class="footer">
    Generated by Troubadour · AI-Powered Music Critique<br/>
    This review was generated by artificial intelligence. Scores and feedback reflect algorithmic analysis, not human judgment.
  </div>
</body>
</html>`;

  return html;
}

export async function exportReviewPdf(
  opts: PdfExportOptions & { userId: number; reviewId: number },
): Promise<{ url: string; filename: string }> {
  const html = await generateReviewPdfHtml(opts);

  const filename = `troubadour-${opts.mode}-${opts.trackName.replace(/[^a-zA-Z0-9]/g, "-").toLowerCase()}.html`;
  const fileKey = `exports/${opts.userId}/${opts.reviewId}/${filename}-${Date.now()}`;

  const { url } = await storagePut(fileKey, Buffer.from(html, "utf-8"), "text/html");

  return { url, filename };
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
